In [8]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv(r'/Users/chengkj/code/self/test/python/wangguowei.csv',encoding='gbk')
df.head()

,客户编号,同一信用代码,本月职位刷新数量,本月职位新增数量,职位总数,渠道,渠道字典,城市,公司规模,行业字典,行业,性质字典,公司性质,电话,本月各职能职位发布累计数量排名前三,各职能职位累计发布数量排名前三
0,a000001,no company,0,0,5,[gj],"[[], [], [], [], [], [gj_106264114]]",[],"[{""from"":10000,""to"":-1}]",[10],[金融/银行/投资/基金/证券],[3],[国企],NaN,[],"[{""qty"":3,""jname"":""综合金融理财规划师（双休）"",""contacts"":[..."
1,a000002,no company,0,0,71,[gj],"[[], [], [], [], [], [gj_105220653]]",[],"[{""from"":10000,""to"":-1}]",[15],[保健按摩],[4],[民营],NaN,[],"[{""qty"":268,""jname"":""服务员包吃住3000多月"",""contacts"":..."
2,a000003,no company,0,0,4,[gj],"[[], [], [], [], [], [gj_106222595]]",[],"[{""from"":10000,""to"":-1}]",[54],[农/林/牧/渔],[10],[上市公司],NaN,[],"[{""qty"":5,""jname"":""520生活圈线上线下连锁机构"",""contacts"":..."
3,a000004,no company,0,0,72,[gj],"[[], [], [], [], [], [gj_106470362]]",[],"[{""from"":1000,""to"":9999}]",[58],[生产/制造],[11],[股份制企业],NaN,[],"[{""qty"":10,""jname"":""3D打印产品设计师 高薪"",""contacts"":[..."
4,a000005,no company,0,0,10,"[gj, lg]","[[], [], [], [lg_263990], [], [gj_106396627]]","[, 广州]","[{""from"":2000,""to"":-1}, {""from"":1000,""to"":9999}]","[0, 6]","[建筑/装修, O2O]","[0, 4]","[, 民营]",NaN,[],"[{""qty"":5,""jname"":""急招家装销售精英"",""contacts"":[{""nam..."

In [188]:
# df['A']= df['渠道'].map(lambda x: x.split(',')[0])
# df['A'], df['B'], df['C'] = df['渠道'].str.split(',',expand=True)
targetSeries = df['渠道']
def transformListToStr(it): 
    val = str(it)
    return val[1:len(val)-1]
def resolveName(name):
    return name.Upper()
    

res = map(transformListToStr, targetList)

# series -> map -> list -> series  x
# series.map
newSeries = targetSeries.map(transformListgToStr).str.split(',',expand=True)

for i in newSeries:
    df['渠道'+str(i+1)] = newSeries[i]
df

df.to_csv("train-gbk-new.csv", encoding='gbk')

'[1, 4, 9, 16, 25]'